# Generated by Django 6.0.5 on 2026-06-03 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeOuOffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_publication', models.CharField(choices=[('offre', 'Offre de mentorat'), ('demande', 'Demande de mentorat')], max_length=10)),
                ('format_seance', models.CharField(choices=[('presentiel', 'Présentiel'), ('en_ligne', 'En ligne'), ('les_deux', 'Les deux')], default='les_deux', max_length=15)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('matche', 'Matché'), ('ferme', 'Fermé')], default='ouvert', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.competence')),
            ],
            options={
                'verbose_name': 'Offre/Demande',
                'db_table': 'mentoring_requests',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_global', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score_competences', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('score_horaires', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('score_filiere', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_attente', max_length=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchings_mentor', to=settings.AUTH_USER_MODEL)),
                ('mentore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchings_mentore', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Matching',
                'db_table': 'match_suggestions',
                'ordering': ['-score_global'],
                'unique_together': {('mentor', 'mentore')},
            },
        ),
    ]
